/**
 * Branded type for Snowflake IDs.
 *
 * Snowflake IDs are 64-bit integers generated by the backend.
 * JavaScript's `Number` only supports safe integers up to 2^53 − 1 (9007199254740991),
 * while Snowflake IDs can be up to 2^63 − 1 (9223372036854775807).
 *
 * RULES:
 *  - Always transfer as `string` over JSON (backend uses @JsonSerialize(ToStringSerializer))
 *  - NEVER convert to `number` — use `+id`, `Number(id)`, `parseInt(id)` etc.
 *  - BigInt is NOT needed: we only compare/display/route with these IDs, never do arithmetic
 *  - Use this branded type to get compile-time protection against accidental `number` usage
 *
 * @example
 *   // Creating
 *   const id = '154477677087035392' as SnowflakeId;
 *
 *   // ✅ Safe operations
 *   console.log(id);                    // display
 *   router.navigate([id]);              // route param
 *   `${apiUrl}/detail/${id}`;           // URL interpolation
 *   id === otherSnowflakeId;            // string equality
 *
 *   // ❌ Compile-time errors (branded type prevents)
 *   const num: number = id;             // Type error
 *   Math.round(id);                     // Type error
 */
export type SnowflakeId = string & { readonly __brand: 'SnowflakeId' };

/**
 * Safely cast a raw string value (from API response or route param) to SnowflakeId.
 * Returns `null` if the input is falsy/empty.
 *
 * @param value - A raw string value from an API response, route param, etc.
 */
export function toSnowflakeId(value: string | null | undefined): SnowflakeId | null {
    if (!value) return null;
    return String(value) as SnowflakeId;
}
